### ISSUE TITLE
TFN results from paper

### ISSUE THREAD

**Issue by rhoposit** [Justin1904/TensorFusionNetworks#1]
Hi, in table 2 of the TFN (2017) paper, there is a reference to performance results for TFN_trimodal and another to TFN. The results are different. What's the difference? Because the data is trimodal, shouldn't they be the same?

**Comment by Justin1904** [comment]
Hi, in the TFN paper, the core idea is to build a tensor representation that contains unimodal + bimodal + trimodal interactions. The full TFN model does that by first appending 1s to each of the modalities and then take the outer product of them (figure 4). However, the trimodal TFN does not append the 1s, and the resulting tensor will only get trimodal interactions, leaving out unimodal and bimodal interactions.
