### ISSUE TITLE
How to apply CMU Multimodal Data SDK into this project

### ISSUE THREAD

**Issue by Menixlee** [Justin1904/TensorFusionNetworks#10]
Firstly:  In the utils.py, I have no idea what is "mmdata" variable

Secondly: After I run the train.py ,  I got error as follow：
Temp location for saving model: models\tfn.pt
Traceback (most recent call last):
Currently using MOSI dataset.
  File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 213, in <module>
    main(PARAMS)
  File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 91, in main
    train_set, valid_set, test_set, input_dims = preprocess(options)
  File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 41, in preprocess
    mosi = MultimodalDataset(dataset, max_len=max_len)
  File "D:\A PROJECT\TensorFusionNetworks-master\utils.py", line 56, in __init__
    self.dataloader = mmdata.__dict__[dataset]()
KeyError: 'MOSI'
It seems it can't find "MOSI" dataset

I have dowload the CMU-Multimodal SDK into this project.
But how to apply it?  set mmdata like "from mmsdk import mmdatasdk as mmdata"? 

I'm looking forward to your reply.
Thanks and Best Regards
Jia Li

**Comment by ohheysherry66** [comment]
> Firstly: In the utils.py, I have no idea what is "mmdata" variable
> 
> Secondly: After I run the train.py , I got error as follow：
> Temp location for saving model: models\tfn.pt
> Traceback (most recent call last):
> Currently using MOSI dataset.
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 213, in 
> main(PARAMS)
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 91, in main
> train_set, valid_set, test_set, input_dims = preprocess(options)
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 41, in preprocess
> mosi = MultimodalDataset(dataset, max_len=max_len)
> File "D:\A PROJECT\TensorFusionNetworks-master\utils.py", line 56, in **init**
> self.dataloader = mmdata.**dict**dataset
> KeyError: 'MOSI'
> It seems it can't find "MOSI" dataset
> 
> I have dowload the CMU-Multimodal SDK into this project.
> But how to apply it? set mmdata like "from mmsdk import mmdatasdk as mmdata"?
> 
> I'm looking forward to your reply.
> Thanks and Best Regards
> Jia Li

Did you figure it out？I met the same problem.Thank you very much.

**Comment by Justin1904** [comment]
> Firstly: In the utils.py, I have no idea what is "mmdata" variable
> 
> Secondly: After I run the train.py , I got error as follow：
> Temp location for saving model: models\tfn.pt
> Traceback (most recent call last):
> Currently using MOSI dataset.
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 213, in 
> main(PARAMS)
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 91, in main
> train_set, valid_set, test_set, input_dims = preprocess(options)
> File "D:/A PROJECT/TensorFusionNetworks-master/train.py", line 41, in preprocess
> mosi = MultimodalDataset(dataset, max_len=max_len)
> File "D:\A PROJECT\TensorFusionNetworks-master\utils.py", line 56, in **init**
> self.dataloader = mmdata.**dict**dataset
> KeyError: 'MOSI'
> It seems it can't find "MOSI" dataset
> 
> I have dowload the CMU-Multimodal SDK into this project.
> But how to apply it? set mmdata like "from mmsdk import mmdatasdk as mmdata"?
> 
> I'm looking forward to your reply.
> Thanks and Best Regards
> Jia Li

This project is quite out of date right now as of data processing pipelines... the SDK has gone through a couple of major changes and I could imagine my code here cannot work as it used to with the new SDK. Though the implementation of the model can still be used as a reference. As for how to use the latest SDK for data processing, you can refer to [this repo](https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials), it is a tutorial written by me to train a simple late fusion model with the new SDK. You could just swap the model there to be TFN.
