### ISSUE TITLE
Weights of audio sub network returning NAN

### ISSUE THREAD

**Issue by purvanshi** [Justin1904/TensorFusionNetworks#6]
The layer1 weights of the audio subnetwork start giving NAN values. Particularly talking about the output of 
`self.linear_1(dropped)`
I tried adjusting the learning rate but it doesn't help.

**Comment by Justin1904** [comment]
Are you using your own data or the datasets from CMU Multimodal SDK? Have you examined if there're NaN values in the input? For the past version of SDK I wrote code for checking and removing inf and nan values manually, it might be the case that in your data or the new version of SDK's data there're also inf or nan values in the input. In my previous experience, this happens in particular with COVAREP acoustic features.

**Comment by purvanshi** [comment]
yes the problem is with acoustic features. The input is nan at several points.
Thanks for the help.
