### ISSUE TITLE
F-score

### ISSUE THREAD

**Issue by EgorLakomkin** [Justin1904/TensorFusionNetworks#9]
Hi,

I am curious why the F-score is returned with the average parameter set to 'binary'? Doesn't it lead to reporting the F-score only for the 1 class, meaning positive sentiment? Wouldnt it be fair to have a macro F-score, where individual negative and positive class performance is averaged? The performance of the 0 class is kind of ignored in the 'binary' setup.

**Comment by Justin1904** [comment]
That's a good point. Let me check with the authors of the paper and get back to you. Though I think in a binary classification case it is also common to just calculate F1 w.r.t positive class.

**Comment by Justin1904** [comment]
I could confirm that the authors used the 'binary' setting in the F1 score. The reasoning behind that I am not exactly sure, but I guess for this particular task the regression loss (i.e. MAE) could reflect how well the model is doing.

**Comment by EgorLakomkin** [comment]
thanks @Justin1904 !
